# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:            Codinfox
tagline:          'Learning to be Giant.'
description:      'Blog of YourName. Here are some technical stuff. Some notes about development.'
url:              http://codinfox.github.io

author:
  name:           'Your Name'
  url:            http://ud803.github.io
  photo:         '/public/imgs/KakaoTalk_20211027_202624829.jpg'
  introduction:   'Some introduction words that will be displayed under the avatar. You may include HTML <a href="#">here</a>.'

paginate:         5
paginate_path:    '/blog/page:num'

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/codinfox/lanyon-codinfox.github.io
